# image will be published to ghcr.io/<user>/<name>
name: my-os
# description will be included in the image's metadata
description: Tudor's OS image, based on Universal Blue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install: [1password]

  - type: files
    files:
      - usr: /usr
      - etc: /usr/etc

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - tailscale
      - swaylock
      - polkit-gnome

      - network-manager-applet
      - blueman

      - langpacks-en # the lingua franca
      - langpacks-en_GB # the Queen's English
      - langpacks-nl # the Nether
      - langpacks-ro # the OG
    remove:

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
      - com.raggesilver.BlackBox
      - org.telegram.desktop
      - com.discordapp.Discord
      - org.videolan.VLC
      - io.github.flattool.Warehouse
      - com.spotify.Client
      - com.google.Chrome # for work...
      - org.gnome.Solanum
      - org.signal.Signal
      - com.github.tchx84.Flatseal
      - org.gimp.GIMP
      - ca.desrt.dconf-editor
      - org.mozilla.Thunderbird
      - org.gnome.NautilusPreviewer
      - org.pulseaudio.pavucontrol
      - org.libreoffice.LibreOffice

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
