on:
  push:
    paths:
      - "boot_menu.yml"
      - ".github/workflows/release-iso.yml"
  workflow_dispatch:

name: release-iso
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate ISO
        uses: jasonn3/build-container-installer@v1.2.0
        id: isogenerator
        with:
          arch: x86_64
          image_name: ${{ github.event.repository.name }}
          image_repo: "ghcr.io/${{ github.repository_owner }}"
          variant: Silverblue
          version: 40
          image_tag: latest
          enable_cache_dnf: false
          enable_cache_skopeo: false
      - name: Upload ISO
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.isogenerator.outputs.iso_path }}
          path: |
            ${{ steps.isogenerator.outputs.iso_path }}
            ${{ steps.isogenerator.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
